apiVersion: v1
kind: Pod
metadata: 
  name: podsecret1
spec: 
  containers:
  - name: opensusepod
    image: httpd
    command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
    volumeMounts:
        - name: secretmnt
          mountPoint: "/mnt"
  volumes:
  - name: secretmnt
    secret:
      secretName: mysecret
