apiVersion: v1
kind: Pod
metadata:
     name: configmap-demo 
     labels:
        purpose: demonstrate-configmaps
spec:
  containers:
    - name: configmap-demo-container
      image: httpd
      envFrom:
        - configMapRef:
             name: my-configmap
